model_name: "bert-base-cased"
train_path: "data/conll2003/train.txt"
valid_path: "data/conll2003/dev.txt"
num_classes: 5
batch_size: 8
lr: 1e-5
weight_decay: 0.0
num_epochs: 5
num_warmup_steps: 0
device: "cuda:2"

